### ISSUE TITLE
What happened to the wiki?

### ISSUE THREAD

**Issue by laanwj** [google/music-synthesizer-for-android#16]
Looks like the DX7 wiki was lost in transition to github. This is unfortunate, as some of the pages were quite interesting. More specifically I'm trying to find the following page:

- https://code.google.com/p/music-synthesizer-for-android/wiki/Dx7Envelope
- http://wiki.music-synthesizer-for-android.googlecode.com/git-history/dfa09620c8ca42697c7af1320edba934802c607d/Dx7Envelope.wiki

Does anyone happen to have a backup?
(internet archive was not helpful either)

**Comment by itsjoesullivan** [comment]
I hope this hasn't been lost. That was an incredible resource.

**Comment by everythingwillbetakenaway** [comment]
its seems lost..

**Comment by everythingwillbetakenaway** [comment]
up again!

https://github.com/google/music-synthesizer-for-android/tree/master/wiki

**Comment by laanwj** [comment]
Thank you so much!
Closing this issue
